### ISSUE TITLE
Visited link colour is very similar to the normal text colour

### ISSUE THREAD

**Issue by leonardehrenfried** [yous/whiteglass#16]
![screen shot 2017-11-12 at 17 51 22](https://user-images.githubusercontent.com/151346/32701238-32f13d16-c7d2-11e7-9db8-cfe547471700.png)

In the above example the word "performance benchmark" is a link but since it's a visited one, it's very hard to recognise that.

Would it be possible to make the colour of visited links more obvious?

**Comment by yous** [comment]
Hi, currently the color of `a:visited` is defined as `darken($brand-color, 10%);`. We can increase that `10%` to `15%` or something. If it's still hard to recognize, then we should think another way, for example, combining [`desaturate`](http://sass-lang.com/documentation/Sass/Script/Functions.html#desaturate-instance_method).

**Comment by yous** [comment]
Also you can change `$brand-color` in `_sass/whiteglass.scss`, so you can check with multiple colors.

**Comment by leonardehrenfried** [comment]
Can I play with this by copying `_sass/whiteglass.scss` into my own jekyll installation?

**Comment by yous** [comment]
`_sass/whiteglass.scss` defines fallback, you can copy `assets/main.scss` to your jekyll site and edit it as you want. See https://github.com/yous/whiteglass/blob/master/README.md#customization.

**Comment by yous** [comment]
Closing this now, and feel free to reopen this or make a new issue if you have a problem.
