### ISSUE TITLE
New folders and files disappear

### ISSUE THREAD

**Issue by toddy86** [yous/whiteglass#21]
This might be a bit of a noob question, so apologies in advance. But every time I create a new folder under the _site parent (e.g. projects) with an index.html file in it, after a few minutes the folder and index.html file disappear. This happens if I create the folders manually in the directory or via my text editor.

Is there a recommended way of creating new folders / pages that I should be following? I didn't have the same issue using a different Jekyll theme, so I am presuming I am not following correct protocol for your theme.

I have read the docs, but have not been able to find any answer. 

Thanks in advance.

Todd

**Comment by toddy86** [comment]
Noob question... Created a new "xxxxx.md" file in the root directory and this created the page correctly for me. Thought I would write a response here in case any other dumb dumbs came across the same issue.

**Comment by yous** [comment]
@toddy86 No problem! If you have any questions or problems, feel free to open a new issue.
