### ISSUE TITLE
How to add images for blog

### ISSUE THREAD

**Issue by papadave66** [yous/whiteglass#27]
I can write the blog in `master` branch and build by travis automaticlly . But I may need to add pictures for my blog text. I found that the `gh_pages` branch  directory is very different with `master` .So how should I create the image directory and include them into the text. Thanks

**Comment by yous** [comment]
You can just make a directory in `master` branch, and link that image using markdown. For example, see [my blog post](https://github.com/yous/yous.be/commit/fc2b067f3fe7760c36e8d0fc02037a3a25266195).

``` markdown
![image alt](/images/image.png "image title")
```

**Comment by papadave66** [comment]
Thanks ! It really helps me a lot!

Chayoung You <notifications@github.com> 于2019年7月7日周日 下午8:48写道：

**Comment by papadave66** [comment]
Thanks . It really helps me a lot!

**Comment by armsp** [comment]
@yous which css file should we modify to control the height and width of the images?

**Comment by yous** [comment]
@armsp If you're using kramdown for markdown renderer (which is default), you can add custom attributes like following:
``` markdown
![image alt](/path/to/image.png "image title"){: width="200" height="200"}
```
Otherwise, I think you should use plain HTML:
``` html
<img alt="image alt" src="/path/to/image.png" title="image title" width="200" heigh="200" />
```
For more markdown options, see <https://jekyllrb.com/docs/configuration/markdown/>.

**Comment by yous** [comment]
For CSS file, you can create your own `assets/main.scss`. See [Customization](https://github.com/yous/whiteglass/blob/master/README.md#customization) section of README.md.
