### ISSUE TITLE
Multilingual theme?

### ISSUE THREAD

**Issue by minac** [yous/whiteglass#3]
Hi!

I love this theme, clean and feature full at the same time.
I've got it [mostly up](http://migueldavid.eu/) and very happy with it.

On to the question/issue: I've seen that the theme [makes use of the lang attribute](https://github.com/yous/whiteglass#locale), but when I create posts with a different language (lang: pt for instance) it still shows up just like any other post on the home page.
Can you please tell me if I am doing something wrong or if there is anything else I need to change in the theme to make this work?

Thanks!

**Comment by yous** [comment]
Hi, thank you for using this theme!

Actually, the `site.lang` and the `post.lang` are only for setting the `lang` attribute of HTML. It's to get benefits from browser or other tools, see ["Why use the language attribute?"](https://www.w3.org/International/questions/qa-lang-why.en) if you want to.

So I think it works as I intended, you can check that `<html>` tag has `lang="pt"` attribute. This theme doesn't separate posts with different languages, and this is also what I intended. It shows the same content wherever a user connects from, whatever language a user uses.

**Comment by minac** [comment]
Can you please help me in identifying which files I would have to change to
make this a multilingual theme? I just need it for the contents of the
posts, not the whole website. Something like a link on the header to change
between EN and PT.

Thanks!

On 6 March 2017 at 02:16:41, Chayoung You (notifications@github.com) wrote:

Hi, thank you for using this theme!

Actually, the site.lang and the post.lang are only for setting the lang
attribute of HTML. It's to get benefits from browser or other tools, see "Why
use the language attribute?"
<https://www.w3.org/International/questions/qa-lang-why.en> if you want to.

So I think it works as I intended, you can check that <html> tag has
lang="pt" attribute. This theme doesn't separate posts with different
languages, and this is also what I intended. It shows the same content
wherever a user connects from, whatever language a user uses.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/yous/whiteglass/issues/3#issuecomment-284286591>, or mute
the thread

**Comment by yous** [comment]
Hi, you can achieve multilingual structure using _categories_. There is a relative issue, https://github.com/jekyll/jekyll/issues/1819.

Configure your website like this:

```
root
|-- index.html
|-- en
|   `-- _posts
|       `-- 2017-03-08-english-post.markdown
`-- pt
    `-- _posts
        `-- 2017-03-08-portuguese-post.markdown
```

And modify your [`permalink`](https://jekyllrb.com/docs/permalinks/) option in `_config.yml`:

``` yml
permalink: /:categories/:year/:month/:day/:title/
```

Then each post in `en` directory will have additional category `en`, each post in `pt` directory will also have category `pt`. If you don't specify any other categories in each post, then the permalink will be:

```
/en/2017/03/08/english-post/
/pt/2017/03/08/portuguese-post/
```

But note that if you have specified other categories, they will appear in the permalink like `/en/tech/2017/03/08/english-post/`.

**Comment by yous** [comment]
Also, I just have found [this commit](https://github.com/kleinfreund/kleinfreund.de/commit/a1d1051688eb9393f93392e98ee26c5466d82214). Like this, you can set an additional attribute, i.e. `lang`, based on the directory structure, and use it to filter them.

``` liquid
{% assign posts_en = site.posts | where:"lang","en" %}
{% assign posts_pt = site.posts | where:"lang","pt" %}
```

If you want to apply filter to `/index.html`, then you need to rewrite it to base on `layout: default`. See [`_layouts/home.html`](https://github.com/yous/whiteglass/blob/master/_layouts/home.html) of this project.

**Comment by minac** [comment]
Hi Chayoung You,

I hacked at the theme for a while and made it multi-lingual. :) I am not
issuing a pull request because I considerably changed things so it would
not be a clean merge, however feel free to pickup any ideas if you like:
https://github.com/minac/minac.github.io

The only thing I did not make multi-lingual is the feed.xml but it should
be quick to do.

I hope this helps.

--
Miguel
migueldavid.eu  - LinkedIn <http://uk.linkedin.com/in/migueldavid/>  - Taste
Porto <https://www.tasteporto.com/>


On 8 March 2017 at 11:12:02, Chayoung You (notifications@github.com) wrote:

Also, I just have found this commit
<https://github.com/kleinfreund/kleinfreund.de/commit/a1d1051688eb9393f93392e98ee26c5466d82214>.
Like this, you can set an additional attribute, i.e. lang, based on the
directory structure, and use it to filter them.

{% assign posts_en = site.posts | where:"lang","en" %}{% assign
posts_pt = site.posts | where:"lang","pt" %}

If you want to apply filter to /index.html, then you need to rewrite it to
base on layout: default. See _layouts/home.html
<https://github.com/yous/whiteglass/blob/master/_layouts/home.html> of this
project.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/yous/whiteglass/issues/3#issuecomment-285014083>, or mute
the thread

**Comment by yous** [comment]
Hi Miguel David,

You made it! I see we have to use _tags_ instead of _categories_ when categories are used for specifying the language. Here I mention [your commit](https://github.com/minac/minac.github.io/commit/f7f6c1499bcb5ed4b982ecc3e33bbc854319ee30) for multi-lingual theme, so anyone who want to make one can get ideas.

I'm yet not sure about making this feature configurable, because of some breaking changes in categories and other structures. If there are many demands, I'll reconsider.

As you seem to resolve the problem, I close this. If you have any other questions, feel free to open a new issue. Thank you for letting me know!

**Comment by minac** [comment]
Hi!

Using tags is something I did last minute because I did not want the URL to
be like example.com/en/aws/cloud/……/2017/
<http://example.com/en/aws/cloud/%E2%80%A6%E2%80%A6/2017/>….
If I left them as categories they would all be in the URL, this way the
categories are there for language only (en/pt) and then tags for the rest.
I completely understand that you don’t want to merge the changes as they
are quite a few (it was an interesting battle against Jekyll and Liquid), I
just wanted to let you know in case you decide got add that in the future.

Have a great day!

--
Miguel
migueldavid.eu  - LinkedIn <http://uk.linkedin.com/in/migueldavid/>  - Taste
Porto <https://www.tasteporto.com/>


On 21 March 2017 at 02:04:08, Chayoung You (notifications@github.com) wrote:

Hi Miguel David,

You made it! I see we have to use *tags* instead of *categories* when
categories are used for specifying the language. Here I mention your commit
<https://github.com/minac/minac.github.io/commit/f7f6c1499bcb5ed4b982ecc3e33bbc854319ee30>
for multi-lingual theme, so anyone who want to make one can get ideas.

I'm yet not sure about making this feature configurable, because of some
breaking changes in categories and other structures. If there are many
demands, I'll reconsider.

As you seem to resolve the problem, I close this. If you have any other
questions, feel free to open a new issue. Thank you for letting me know!

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/yous/whiteglass/issues/3#issuecomment-287954509>, or mute
the thread

**Comment by yous** [comment]
Yes, that's right. As categories are used for languages, they should be empty by default (no specific languages), then URLs will be <http://example.com/2017/03/21/some-post-name/>.

As jekyll-archives also support archive pages for [tags](https://github.com/jekyll/jekyll-archives/blob/master/docs/configuration.md), I can consider completely replacing categories with tags. Then even the theme doesn't support the native multi-lingual feature, it's still free and easy to use categories as user want because the theme doesn't use them. This can be the next milestone!
