### ISSUE TITLE
Github can't find file to @import "whiteglass"; 

### ISSUE THREAD

**Issue by SumaiyaR** [yous/whiteglass#33]
Hello, 

My site builds locally, but I get this error when I push to github. 

Your SCSS file `blog/assets/main.scss` has an error on line 45: File to import not found or unreadable: whiteglass. Load path: /hoosegow/.bundle/ruby/2.5.0/gems/jekyll-theme-primer-0.5.4/_sass.

I have tried with the remote_theme as in the previous issue, but I still get the same error.

**Comment by yous** [comment]
What happens if you move files under `/blog/` of your repository to `/`? Currently your repository has only one entry, `blog`, so maybe the problem is because GitHub can't recognize Gemfile, _config.yml, etc.

**Comment by yous** [comment]
It seems that your site is working now, so closing this. If you have a problem with whiteglass, feel free to open a new issue.
