### ISSUE TITLE
The location for main.css in index.html inside _site folder is incorrect

### ISSUE THREAD

**Issue by armsp** [yous/whiteglass#34]
I built a blog using your theme. However I am yet to figure out how to use GitHub Pages to work with it since you said that `jekyll-archives` wont play well with it. One option is to just publish the contents of `_site` folder so that GitHub Pages just renders `index.html`. However when that happened the css didn't work at all. When I looked at the `link` tag I noticed that location for `main.css` was - ```  <link rel="stylesheet" href="/whiteglass/assets/main.css">``` but there is NO `whiteglass` folder in `_site`.

How do I solve this so that whenever I do jekyll serve, everything is built properly?

**Comment by yous** [comment]
I think it's because you have `baseurl: "/whiteglass"` in your `_config.yml`. If you want to use `armsp.github.io` as home of your blog, set `baseurl: ""`. You may want to use `armsp.github.io/blog` as home, then set `baseurl: "/blog"`.

**Comment by armsp** [comment]
I am not using it as a personal site, just a project page. So by default GitHub gives the URL as ```https://armsp.github.io/<repository-name>```

In this case should I keep `baseurl: "/<repository-name>"` or `baseurl: ""`

**Comment by yous** [comment]
Please try changing `_config.yml` as the following:
``` yml
baseurl: "/testing-whiteglass"
url: "https://armsp.github.io"
```
It's correct even if you don't have the folder called `repository-name`, as it's URL. `<url><baseurl>` will point the URL of the repository's GitHub Pages (in this case, `https://armsp.github.io/testing-whiteglass`). `index.html` will have `<url><baseurl>/assets/main.css`, and you have `assets/main.css` under your repository, it will load the CSS correctly.

**Comment by armsp** [comment]
It works !! I can't thank you enough.
Just one last question....should this have its own domain, then `url: "https://armsp.github.io"` will need to be changed to `url: "https://abc.com"` with `baseurl: ""`, right?

**Comment by yous** [comment]
Yes, if you want to give `abc.com` as home, that's right.

**Comment by armsp** [comment]
Great, closing this now. Thanks a lot once again!!

**Comment by yous** [comment]
No problem! Always feel free to open a new issue if you have problems.
