### ISSUE TITLE
Is there support for favicons?

### ISSUE THREAD

**Issue by armsp** [yous/whiteglass#36]
Am I correct in observing that whiteglass has no support for favicons right now?

If I need to provide support then I have to edit `head.html` with maybe one of the solutions from [here](https://stackoverflow.com/questions/30551501/unable-to-set-favicon-using-jekyll-and-github-pages)?

**Comment by yous** [comment]
Hi, you can put `_includes/head_custom.html` for setting favicons. See [Customization](https://github.com/yous/whiteglass/blob/master/README.md#customization) section of README.md.

``` liquid
<link rel="icon" type="image/x-icon" href="{{ "/favicon.ico" | relative_url }}">
```

Also, this is [`_includes/head_custom.html`](https://github.com/yous/yous.be/blob/source/_includes/head_custom.html) of my blog, you can take a look.

**Comment by armsp** [comment]
Works now !
