### ISSUE TITLE
How to reverse the order of posts in the home page?

### ISSUE THREAD

**Issue by armsp** [yous/whiteglass#38]
Showing blog posts reverse chronological order makes sense. But if you are using this template for something other than a blog, like a poetry anthology or chapters of a book then it makes sense to show the oldest entry first.
Is there any way to do that?
I looked up the `jekyll-paginate` plugin but it looks like its no longer under active development or have support for [reverse pagination](https://github.com/jekyll/jekyll-paginate/issues/28).

I found that a backwards compatible plugin exists - [`jekyll-paginate-v2`](https://github.com/sverrirs/jekyll-paginate-v2)

Any idea on how to make the entries in the home page appear in a chronological order?

**Comment by armsp** [comment]
@yous Do you think its possible to show the blog posts in chronological order?

**Comment by yous** [comment]
I think you need to use other plugins like jekyll-paginate-v2 as you mentioned. But currently, I don't consider switching to jekyll-paginate-v2 as it's not supported on GitHub Pages by default.

**Comment by armsp** [comment]
@yous Okay, in that case, can we do something in the code base itself to change it? I really want to change the order because I am working on an online book using your template, so I was thinking if its possible to show *Chapter 1* before *Chapter 3*, it would be great.

**Comment by yous** [comment]
1. Add `gem 'jekyll-paginate-v2'` to your `Gemfile`, and run `bundle install`
2. Add `jekyll-paginate-v2` to your `plugins` list in your `_config.yml`:
   ``` yml
   plugins:
     - jekyll-archives
     - jekyll-paginate-v2
     - jekyll-sitemap
   ```
3. Add following lines to your `_config.yml`:
   ``` yml
   pagination:
     enabled: true
     permalink: '/posts/:num/'
     sort_reverse: false
   ```
4. Add following lines to the frontmatter of your `index.html`/`index.md`:
   ``` markdown
   ---
   layout: home
   pagination:
     enabled: true
   ---
   ```
   Previously, your `index.html`/`index.md` would look like:
   ``` markdown
   ---
   layout: home
   ---
   ```

**Comment by yous** [comment]
This will reverse the order, but pagination will show next page as "Older" posts, so you may want to override the pagination.

Make `_includes/pagination.html`, and save it with the following lines:
``` liquid
{% if paginator.total_pages > 1 %}
  <div class="pagination">
    {% if paginator.previous_page %}
      <a class="previous" href="{{ paginator.previous_page_path | relative_url }}">&laquo; Previous</a>
    {% endif %}

    {% if paginator.next_page %}
      <a class="next" href="{{ paginator.next_page_path | relative_url }}">Next &raquo;</a>
    {% endif %}
  </div>
{% endif %}
```

**Comment by armsp** [comment]
@yous I had got `jekyll-paginate-v2` working. But I didn't know how to fix the "older" and "newer" issue. It looks like you solved that too. I had raised this issue yesterday on their repo https://github.com/sverrirs/jekyll-paginate-v2/issues/194
Thanks a lot for your continued support. I will test this asap and close this issue once everything works.
