### ISSUE TITLE
Remove use of JEKYLL_PAT

### ISSUE THREAD

**Issue by MichaelCurrin** [yous/whiteglass#41]
This relates to PR in the template repo - yous/whiteglass-template#3

**Comment by MichaelCurrin** [comment]
After that is merged, this theme repo needs changes to make the steps lighter.

README
https://github.com/yous/whiteglass#quick-start

About
https://github.com/yous/whiteglass/blob/1bab7eb3f9a5ee20c9911f84bd42084609a6aaee/about.md#quick-start

Travis? It uses the GITHUB_TOKEN name but has a comment which might no longer be relevant 
https://github.com/yous/whiteglass/blob/1bab7eb3f9a5ee20c9911f84bd42084609a6aaee/.travis.yml#L31

**Comment by yous** [comment]
Thanks, I've just updated the README.md and about.md.

Travis CI still seems to use `github_token`: https://docs.travis-ci.com/user/deployment/pages/, so I leave it as is.
