### ISSUE TITLE
New blog - all posts are under "Archives"

### ISSUE THREAD

**Issue by gkgaurav31** [yous/whiteglass#43]
I am trying to create a new blog. Changed the theme to whiteglass. I just have 1 post. I can see it under Archives, but not in the home page. How can I fix it?

**Comment by yous** [comment]
It seems that I'm little bit late. I guess you're building a blog based on <https://github.com/gkgaurav31/code>, but it has `.nojekyll` file, which prevents Jekyll to process. You may have to use other branch for actual site: `gh-pages`, for example.

[jekyll-theme-chirpy](https://github.com/cotes2020/jekyll-theme-chirpy) has template repository called [chirpy-starter](https://github.com/cotes2020/chirpy-starter). Go to the link, click "Use this template" button. whiteglass also has a template repository, [whiteglass-template](https://github.com/yous/whiteglass-template). Using template will be easier than modifying a fork.

**Comment by yous** [comment]
Also, IIRC, there was empty `url` in _config.yml when you're using whiteglass theme. This can be the reason why home page didn't get rendered, but I'm not sure.

**Comment by yous** [comment]
The issue seems to be resolved now, so closing this.
