### ISSUE TITLE
Modify my i18n.yml

### ISSUE THREAD

**Issue by Vctrsnts** [yous/whiteglass#52]
Hi.

I modify my `i18n.yml` with words on catalan and spanish. How I put this modification for you?

Thanks for your work

**Comment by yous** [comment]
Hi, you can fork this repository, and add your translation to `i18n.yml`, and then make a pull request.

Refer this link: <https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request>
