### ISSUE TITLE
Keywords im YAML Front Matter

### ISSUE THREAD

**Issue by Weishaupt** [yous/whiteglass#7]
Why are keywords a comma-separated list, instead of sequence inside the `keyword`-mapping like

    keyword:
      - food
      - recipe
      - avocado

Right now the keywords cannot be processed for anything else, if I understand this correctly.

Great theme by the way. 😊

**Comment by yous** [comment]
Hi @Weishaupt, thank you for the report!

As keywords of `meta` tag should be a comma-separated list, it just uses the input as-is so we can avoid an accident comma in one keyword. For now, it's used on `_includes/head.html` only.

But if you want to use them in somewhere else, you can use [`split`](https://help.shopify.com/themes/liquid/filters/string-filters#split) to `page.keywords`, for example:

``` liquid
{% assign words = page.keywords | split ', ' %}
{% for word in words %}
  {{ word }}
{% endfor %}
```

Also, if you still want to assign keywords using list, please let me know your thoughts.

**Comment by Weishaupt** [comment]
Hey Yous,

thank you for the reply. I'd consider the YAML sequence style more intuitive, because it is inside the YAML block. Of course this is just convention.

For further processing (like a list of keywords or something) I'd figure the YAML syntax easier for processing, too.

**Comment by yous** [comment]
Yes, we can make the theme to handle `keywords` of an array. Past posts use `keywords` of a string, so I think it's backward compatible.

**Comment by yous** [comment]
I just updated to support list for keywords in fe32072527e70bb57ef8135dc49a2700992d7f6b, so please have a look.
