### ISSUE TITLE
Highlight current page in navigation

### ISSUE THREAD

**Issue by Weishaupt** [yous/whiteglass#9]
I'd like to have a visual highlight (e.g. boldface) if you visit a page that is part of the navigation. Currently, there is no hint as to what page of the navigation you're on.

A possible solution could be [this SO answer](http://stackoverflow.com/a/6369044/1403593).

**Comment by yous** [comment]
Thank you for suggesting a new feature, but I don't have a plan for adding such styles to the navigation.

You can still override `_includes/header.html` for that needs. I suggest the following for your `_includes/header.html`:

``` liquid
<header class="site-header">

  <div class="wrapper">

    <a class="site-title" href="{{ "/" | relative_url }}">{{ site.title | escape }}</a>

    <nav class="site-nav">
      {% for link in site.data.navigation.main %}
        {% assign current = nil %}
        {% if page.url == link.url %}
          {% assign current = "current" %}
        {% endif %}
        {% if link.url contains "http" %}
          {% assign url = link.url %}
        {% else %}
          {% assign url = link.url | relative_url %}
        {% endif %}
        <a class="page-link{% if current %} {{ current }}{% endif %}" href="{{ url }}">{{ link.title }}</a>
      {% endfor %}
    </nav>

  </div>

</header>
```

It will add `current` class to the current navigation link. Copy the `assets/main.scss` from the theme if you don't have it, then add custom styles to your `assets/main.scss`:

``` sass
// ...
@import "whiteglass";

.site-nav {
  .page-link.current {
    font-weight: bold;
  }
}
```

**Comment by Weishaupt** [comment]
Thank you, I'll try it out. May I ask why you don't want such a visual cue by default?

**Comment by yous** [comment]
Because I set proper `<h1>` tag for each page, and I want to keep this theme looking as minimal as possible.
